server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    liquibase:
      change-log: classpath:db/migration/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

security:
  jwt:
    secret: your_jwt_secret_key
    expiration-ms: 3600000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
